routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (Auth::guest()) {
        return view('welcome');
    } else {
        return redirect()->route('home');
    }
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware('auth')->group(function () {
    Route::resource('earnings', 'EarningController', [
        'except' => [
            'show',
        ],
    ]);

    Route::resource('earnings_categories', 'EarningsCategoryController', [
        'except' => [
            'show',
        ],
    ]);
    Route::resource('expenses', 'ExpenseController', [
        'except' => [
            'show',
        ],
    ]);

    Route::resource('expenses_categories', 'ExpensesCategoryController', [
        'except' => [
            'show',
        ],
    ]);

    Route::get('/balance', 'BalanceController@index')->name('balance.index');

    Route::get('/budget', 'BudgetController@index')->name('budget.index');

    Route::get('/budget/create', 'BudgetController@create')->name('budget.create');
    Route::middleware('date')->group(function () {
        Route::get('/budget/{year}/{month}/edit', 'BudgetController@edit')->name('budget.edit');
        Route::put('/budget/{year}/{month}', 'BudgetController@update')->name('budget.update');
        Route::get('/budget/{year}/{month}/confirm', 'BudgetController@confirm')->name('budget.confirm');
        Route::delete('/budget/{year}/{month}', 'BudgetController@destroy')->name('budget.destroy');

    });
    Route::post('/budget', 'BudgetController@store')->name('budget.store');

    Route::get('/overview', 'BalanceController@overview');

});

app/Earning.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Earning extends Model
{
    /**
     * Get earnings category.
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function category()
    {
        return $this->belongsTo('App\EarningsCategory', 'earnings_category_id');
    }
    
    /**
     * Get user.
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/EarningController.php
<?php

namespace App\Http\Controllers;

use App\Earning;
use App\EarningsCategory;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Gate;
use Illuminate\Validation\Rule;

class EarningController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param  Request  $request
     * @return Response
     */
    public function index(Request $request)
    {
        $where = [];
        if ($request->date_from) {
            $where[] = ['date', '>=', $request->date_from];
        }
        if ($request->date_to) {
            $where[] = ['date', '<=', $request->date_to];
        }
        if ($request->category) {
            $where[] = ['earnings_category_id', $request->category];
        }
        $earnings = Earning::where('user_id', Auth::user()->id)->where($where)->orderBy('date', 'desc')
                           ->orderBy('created_at', 'desc')->with('category')->paginate(20);
        $categories = EarningsCategory::where('user_id', Auth::user()->id)->orderBy('name', 'asc')->get();

        return view('earnings.index', ['earnings' => $earnings, 'categories' => $categories, 'request' => $request]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $earningsCategories = EarningsCategory::where('user_id', Auth::user()->id)->orderBy('name', 'asc')->get();

        return view('earnings.create', ['earningsCategories' => $earningsCategories]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'date' => 'required|date|after:2016-12-31',
            'category' => Rule::exists('earnings_categories', 'id')->where(function ($query) {
                $query->where('user_id', Auth::user()->id);
            }),
            'sum' => 'required|numeric|between:0,9999999.99',
            'comment' => 'nullable|string|max:191',
        ]);
        $earning = new Earning();
        $earning->date = $request->date;
        $earning->earnings_category_id = $request->category;
        $earning->sum = $request->sum;
        $earning->comment = $request->comment;
        $earning->user_id = Auth::user()->id;
        $earning->save();

        return redirect()->back()->with([
            'success' => true,
            'message' => 'Pajamos sėkmingai pridėtos',
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Earning  $earning
     * @return Response
     */
    public function edit(Earning $earning)
    {
        if (Gate::allows('earnings.edit', $earning)) {
            $earningsCategories = EarningsCategory::where('user_id', Auth::user()->id)->orderBy('name', 'asc')->get();

            return view('earnings.edit', ['earning' => $earning, 'earningsCategories' => $earningsCategories]);
        } else {
            abort(401, 'Šios pajamos nepriklauso vartotojui.');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  \App\Earning  $earning
     * @return Response
     */
    public function update(Request $request, Earning $earning)
    {
        if (Gate::allows('earnings.edit', $earning)) {
            $request->validate([
                'date' => 'required|date|after:2016-12-31',
                'category' => Rule::exists('earnings_categories', 'id')->where(function ($query) {
                    $query->where('user_id', Auth::user()->id);
                }),
                'sum' => 'required|numeric|between:0,9999999.99',
                'comment' => 'nullable|string|max:191',
            ]);
            $earning->date = $request->date;
            $earning->earnings_category_id = $request->category;
            $earning->sum = $request->sum;
            $earning->comment = $request->comment;
            $earning->save();

            return redirect()->route('earnings.index',
                [date('Y', strtotime($earning->date)), date('m', strtotime($earning->date))])->with([
                'success' => true,
                'message' => 'Pajamos sėkmingai atnaujintos',
            ]);

        } else {
            abort(401, 'Šios pajamos nepriklauso vartotojui.');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Earning  $earning
     * @return Response
     * @throws \Exception
     */
    public function destroy(Earning $earning)
    {
        if (Gate::allows('earnings.edit', $earning)) {
            $earning->delete();

            return redirect()->back()->with([
                'success' => true,
                'message' => 'Pajamos ' . $earning->date . ' ' . $earning->category->name . ', suma: ' . $earning->sum .
                             '  ištrintos.',
            ]);
        } else {
            abort(401, 'Šios pajamos nepriklauso vartotojui.');
        }
    }

}

resources/views/earnings/categories/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @if (session('success'))
            <div class="row justify-content-md-center">
                <div class="col-md-8">
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ session('message') }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </div>
            </div>
        @endif
    </div>

    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-md-8">
                <div class="card border-dark">
                    <div class="card-header bg-dark text-light">Pridėti pajamų kategoriją</div>
                    <div class="card-body">
                        <form role="form" method="POST" action="{{ route('earnings_categories.store') }}">
                            {!! csrf_field() !!}

                            <div class="form-group row">
                                <label for="name" class="col-lg-4 col-form-label text-lg-right">Pavadinimas</label>

                                <div class="col-lg-6">
                                    <input id="name"
                                           type="text"
                                           class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                                           name="name"
                                           value="{{ old('name') }}"
                                           autofocus
                                           required
                                    >
                                    @if ($errors->has('name'))
                                        <div class="invalid-feedback">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </div>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-lg-6 offset-lg-4">
                                    <button type="submit" class="btn btn-dark">
                                        Pridėti
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/earnings/categories/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @if (session('success') !== null)
            <div class="row justify-content-md-center">
                <div class="col-md-8">

                    @if (session('success'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            {{ session('message') }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    @endif

                </div>
            </div>
        @endif
    </div>

    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-md-8">
                <div class="card border-dark">
                    <div class="card-header bg-dark text-light">Redaguoti pajamų kategoriją</div>
                    <div class="card-body">
                        <form role="form" method="POST" action="{{ route('earnings_categories.update', $category->id) }}">
                            {{ method_field('PUT') }}
                            {!! csrf_field() !!}

                            <div class="form-group row">
                                <label for="name" class="col-lg-4 col-form-label text-lg-right">Pavadinimas</label>

                                <div class="col-lg-6">
                                    <input id="name"
                                           type="text"
                                           class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                                           name="name"
                                           value="{{ old('name') ? old('name') : $category->name }}"
                                           autofocus
                                           required
                                    >
                                    @if ($errors->has('name'))
                                        <div class="invalid-feedback">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </div>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-lg-6 offset-lg-4">
                                    <button type="submit" class="btn btn-dark">
                                        Atnaujinti
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/earnings/categories/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-md-8">
                <div class="row">

                    <div class="col-md-8">
                        @if (session('success') !== null)
                            @if (session('success'))
                                <div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
                                    {{ session('message') }}
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            @else
                                <div class="alert alert-danger alert-dismissible fade show mb-0" role="alert">
                                    Klaida! {{ session('message') }}
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            @endif
                        @endif
                    </div>

                </div>
            </div>

        </div>
    </div>

    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-md-8">
                <div class="card border-dark">
                    <div class="card-header bg-dark text-light">Pajamų kategorijos
                        <i class="fas fa-question-circle" data-toggle="popover" data-placement="right"
                           data-content="Šioje skiltyje pateikiamas Jūsų pajamų kategorijų sąrašas."></i>
                    </div>
                    <div class="card-body">
                        <table class="table table-sm table-hover">
                            <thead>
                            <tr>
                                <th>Pavadinimas</th>
                                <th>Redaguoti</th>
                                <th>Ištrinti</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach ($categories as $category)
                                <tr>
                                    <td>{{ $category->name }}</td>
                                    <td>
                                        <a href="{{ route('earnings_categories.edit', $category->id) }}"
                                           class="btn btn-primary btn-sm">
                                            <span class="fas fa-pencil-alt"></span>
                                        </a>
                                    </td>
                                    <td>
                                        <form method="post"
                                              action="{{ route('earnings_categories.destroy', $category->id) }}">
                                            {{ method_field('DELETE') }}
                                            {!! csrf_field() !!}
                                            <button type="submit"
                                                    class="btn btn-danger btn-sm">
                                                <span class="fas fa-trash-alt"></span>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection