routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (Auth::guest()) {
        return view('welcome');
    } else {
        return redirect()->route('home');
    }
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware('auth')->group(function () {
    Route::resource('earnings', 'EarningController', [
        'except' => [
            'show',
        ],
    ]);

    Route::resource('earnings_categories', 'EarningsCategoryController', [
        'except' => [
            'show',
        ],
    ]);
    Route::resource('expenses', 'ExpenseController', [
        'except' => [
            'show',
        ],
    ]);

    Route::resource('expenses_categories', 'ExpensesCategoryController', [
        'except' => [
            'show',
        ],
    ]);

    Route::get('/balance', 'BalanceController@index')->name('balance.index');

    Route::get('/budget', 'BudgetController@index')->name('budget.index');

    Route::get('/budget/create', 'BudgetController@create')->name('budget.create');
    Route::middleware('date')->group(function () {
        Route::get('/budget/{year}/{month}/edit', 'BudgetController@edit')->name('budget.edit');
        Route::put('/budget/{year}/{month}', 'BudgetController@update')->name('budget.update');
        Route::get('/budget/{year}/{month}/confirm', 'BudgetController@confirm')->name('budget.confirm');
        Route::delete('/budget/{year}/{month}', 'BudgetController@destroy')->name('budget.destroy');

    });
    Route::post('/budget', 'BudgetController@store')->name('budget.store');

    Route::get('/overview', 'BalanceController@overview');

});

resources/views/expenses/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @if (session('success'))
            <div class="row justify-content-md-center">
                <div class="col-md-8">
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ session('message') }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </div>
            </div>
        @endif
    </div>

    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-md-8">
                <div class="card border-dark">
                    <div class="card-header bg-dark text-light">Pridėti išlaidas</div>
                    <div class="card-body">
                        <form role="form" method="POST" action="{{ route('expenses.store') }}">
                            {!! csrf_field() !!}

                            <div class="form-group row">
                                <label for="date" class="col-lg-4 col-form-label text-lg-right">Data</label>

                                <div class="col-lg-6">
                                    <input id="date"
                                           type="text"
                                           class="form-control{{ $errors->has('date') ? ' is-invalid' : '' }} datepicker"
                                           name="date"
                                           value="{{ old('date') ? old('date') : date('Y-m-d') }}"
                                           required
                                    >
                                    @if ($errors->has('date'))
                                        <div class="invalid-feedback">
                                            <strong>{{ $errors->first('date') }}</strong>
                                        </div>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="category"
                                       class="col-lg-4 col-form-label text-lg-right">Kategorija</label>
                                <div class="col-lg-6">
                                    <select id="category" class="custom-select form-control{{ $errors->has('category') ? ' is-invalid' : '' }}" name="category" required>
                                        <option value="">-- Pasirinkite --</option>
                                        @foreach ($expensesCategories as $expensesCategory)
                                            <option value="{{ $expensesCategory->id }}"{{ (int)old('category') === (int)$expensesCategory->id ? ' selected' : '' }}>{{ $expensesCategory->name }}</option>
                                        @endforeach
                                    </select>
                                    @if ($errors->has('category'))
                                        <div class="invalid-feedback">
                                            <strong>{{ $errors->first('category') }}</strong>
                                        </div>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="sum" class="col-lg-4 col-form-label text-lg-right">Suma</label>

                                <div class="col-lg-6">
                                    <input id="sum"
                                           type="text"
                                           class="form-control{{ $errors->has('sum') ? ' is-invalid' : '' }}"
                                           name="sum"
                                           value="{{ old('sum') }}"
                                           required
                                    >
                                    @if ($errors->has('sum'))
                                        <div class="invalid-feedback">
                                            <strong>{{ $errors->first('sum') }}</strong>
                                        </div>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="comment" class="col-lg-4 col-form-label text-lg-right">Komentaras</label>

                                <div class="col-lg-6">
                                    <input id="comment"
                                           type="text"
                                           class="form-control{{ $errors->has('comment') ? ' is-invalid' : '' }}"
                                           name="comment"
                                           value="{{ old('comment') }}"
                                    >
                                    @if ($errors->has('comment'))
                                        <div class="invalid-feedback">
                                            <strong>{{ $errors->first('comment') }}</strong>
                                        </div>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-lg-6 offset-lg-4">
                                    <button type="submit" class="btn btn-dark">
                                        Pridėti
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/expenses/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @if (session('success'))
            <div class="row justify-content-md-center">
                <div class="col-md-8">
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ session('message') }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                </div>
            </div>
        @endif
    </div>

    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-md-8">
                <div class="card border-dark">
                    <div class="card-header bg-dark text-light">Pridėti išlaidas</div>
                    <div class="card-body">
                        <form role="form" method="POST" action="{{ route('expenses.update', $expense->id) }}">
                            {{ method_field('PUT') }}
                            {!! csrf_field() !!}

                            <div class="form-group row">
                                <label for="date" class="col-lg-4 col-form-label text-lg-right">Data</label>

                                <div class="col-lg-6">
                                    <input id="date"
                                           type="text"
                                           class="form-control{{ $errors->has('date') ? ' is-invalid' : '' }} datepicker"
                                           name="date"
                                           value="{{ old('date') ? old('date') : $expense->date }}"
                                           required
                                    >
                                    @if ($errors->has('date'))
                                        <div class="invalid-feedback">
                                            <strong>{{ $errors->first('date') }}</strong>
                                        </div>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="category"
                                       class="col-lg-4 col-form-label text-lg-right">Kategorija</label>
                                <div class="col-lg-6">
                                    <select id="category"
                                            class="custom-select form-control{{ $errors->has('category') ? ' is-invalid' : '' }}"
                                            name="category" required>
                                        <option value="">-- Pasirinkite --</option>
                                        @foreach ($expensesCategories as $expensesCategory)
                                            <option value="{{ $expensesCategory->id }}"{{ old('category') ?
                                            ((int)old('category') === (int)$expensesCategory->id ? ' selected' : '') :
                                            ((int)$expense->expenses_category_id === (int)$expensesCategory->id ?
                                            ' selected' : '') }}>{{ $expensesCategory->name }}</option>
                                        @endforeach
                                    </select>
                                    @if ($errors->has('category'))
                                        <div class="invalid-feedback">
                                            <strong>{{ $errors->first('category') }}</strong>
                                        </div>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="sum" class="col-lg-4 col-form-label text-lg-right">Suma</label>

                                <div class="col-lg-6">
                                    <input id="sum"
                                           type="text"
                                           class="form-control{{ $errors->has('sum') ? ' is-invalid' : '' }}"
                                           name="sum"
                                           value="{{ old('sum') ? old('sum') : $expense->sum }}"
                                           required
                                    >
                                    @if ($errors->has('sum'))
                                        <div class="invalid-feedback">
                                            <strong>{{ $errors->first('sum') }}</strong>
                                        </div>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="comment" class="col-lg-4 col-form-label text-lg-right">Komentaras</label>

                                <div class="col-lg-6">
                                    <input id="comment"
                                           type="text"
                                           class="form-control{{ $errors->has('comment') ? ' is-invalid' : '' }}"
                                           name="comment"
                                           value="{{ old('comment') ? old('comment') : $expense->comment }}"
                                    >
                                    @if ($errors->has('comment'))
                                        <div class="invalid-feedback">
                                            <strong>{{ $errors->first('comment') }}</strong>
                                        </div>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-lg-6 offset-lg-4">
                                    <button type="submit" class="btn btn-dark">
                                        Atnaujinti
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/expenses/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container mb-3">
        <div class="row justify-content-md-center">
            <div class="col-md-12">
                <div class="row">

                    <div class="col-md-8 mb-lg-0 mb-md-0 mb-xl-0">
                        @if (session('success') !== null)
                            @if (session('success'))
                                <div class="alert alert-success alert-dismissible fade show mb-0" role="alert">
                                    {{ session('message') }}
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            @else
                                <div class="alert alert-danger alert-dismissible fade show mb-0" role="alert">
                                    Klaida! {{ session('message') }}
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            @endif
                        @endif
                    </div>

                </div>
            </div>

        </div>
    </div>

    <div class="container mb-3">
        <div class="card border-dark">
            <div class="card-header bg-dark text-light">
                <div class="row">
                    <div class="col">Išlaidos {{ $request->date_from }} - {{ $request->date_to }}
                        <i class="fas fa-question-circle" data-toggle="popover" data-placement="right"
                           data-content="Šioje skiltyje pateikiamos Jūsų pasirinkto laikotarpio išlaidos."></i>
                    </div>
                    <div class="col text-right">
                        <button class="btn btn-sm btn-light text-dark" type="button" data-toggle="collapse"
                                data-target="#dates" aria-expanded="false" aria-controls="dates">Filtras
                        </button>
                    </div>
                </div>
            </div>
            <div id="dates" class="collapse">
                <div class="card-body">
                    <div class="row">
                        <form class="form-inline" method="GET" action="{{ route('expenses.index') }}">
                            <label for="date_from" class="sr-only"></label>
                            <input id="date_from" name="date_from" class="form-control datepicker mr-2"
                                   value="{{ $request->date_from }}" placeholder="Data nuo">

                            <label for="date_to" class="sr-only"></label>
                            <input id="date_to" name="date_to" class="form-control datepicker mr-2"
                                   value="{{ $request->date_to }}" placeholder="Data iki">

                            <label for="category" class="sr-only"></label>
                            <select id="category" name="category" class="form-control mr-2">
                                <option value="">-- Kategorija --</option>
                                @foreach ($categories as $category)
                                    <option value="{{ $category->id }}"
                                            {{ $request->category == $category->id ? 'selected' : '' }}>{{ $category->name }}</option>
                                @endforeach
                            </select>

                            <button type="submit" class="btn btn-primary">Filtruoti</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="container">
        <div class="card border-dark">
            <div class="table-responsive">

                <table class="table table-sm">
                    <thead>
                    <tr>
                        <th>Data</th>
                        <th>Kategorija</th>
                        <th class="text-right">Suma</th>
                        <th>Komentaras</th>
                        <th>Redaguoti</th>
                        <th>Ištrinti</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($expenses as $expense)
                        <tr>
                            <td>{{ $expense->date }}</td>
                            <td>{{ $expense->category ? $expense->category->name : '' }}</td>
                            <td class="text-right">{{ number_format($expense->sum, 2) }}</td>
                            <td>{{ $expense->comment }}</td>
                            <td><a href="{{ route('expenses.edit', $expense->id) }}"
                                   class="btn btn-sm btn-success text-light"><span class="fas fa-pencil-alt"></span></a>
                            </td>
                            <td>
                                <form method="post"
                                      action="{{ route('expenses.destroy', $expense->id) }}">
                                    {{ method_field('DELETE') }}
                                    {!! csrf_field() !!}
                                    <button type="submit"
                                            class="btn btn-danger btn-sm">
                                        <span class="fas fa-trash-alt"></span>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach

                    </tbody>
                </table>

                {{ $expenses->appends(['date_from' => $request->date_from, 'date_to' => $request->date_to,
                        'category' => $request->category])->links() }}

            </div>
        </div>
    </div>
@endsection